version: '3.4'
services: 
  orion:
    build: 
      target: base
    command: "yarn start:dev"
    environment: 
      NODE_ENV: development
    volumes: 
      - .:/orion
      - /orion/node_modules