version: '3.4'

services:
  arangodb:
    container_name: arangodb
    logging: 
      driver: none
    image: arangodb/arangodb:latest
    environment:
      - ARANGO_ROOT_PASSWORD=root
    volumes:
      - ./.docker/arangodb/database:/var/lib/arangodb
      - ./.docker/arangodb/apps:/var/lib/arangodb-apps
    ports:
      - "8529:8529"
    networks: 
      - orion
  orion:
    build: 
      context: .
      dockerfile: Dockerfile
      target: prod
    image: open-hotel/orion
    container_name: orion
    working_dir: /orion
    tty: true
    stdin_open: true
    environment: 
      NODE_ENV: production
    expose:
      - "3000"
    links: 
      - arangodb
    depends_on: 
      - arangodb
    networks: 
      - orion
networks:
  orion: